CREATE LANGUAGE plpython3u;
CREATE EXTENSION chajda;

CREATE TABLE example (
    id SERIAL PRIMARY KEY,
    lang_iso TEXT,
    lang_name TEXT,
    doc TEXT
);

INSERT INTO example (lang_iso, lang_name, doc) VALUES
    ('ar', 'arabic', 'هذا هو جملتي التجريبية التي أقوم بوضعها في ترجمة Google لإنشاء حالات اختبار.'),
    ('da', 'danish', 'Dette er mit eksempel test sætning, som jeg lægger i Google Translate for at generere testsager.'),
    ('de', 'german', 'Dies ist mein Beispiel-Testsatz, den ich in Google Translate einfüge, um Testfälle zu generieren.'),
    ('el', 'greek', 'Αυτή είναι η παραδειγματική δοκιμαστική πρόταση που βάζω στη Μετάφραση Google για τη δημιουργία δοκιμαστικών περιπτώσεων.'),
    ('en', 'english', 'This is my example test sentence that I''m putting into Google Translate to generate test cases.'),
    ('es', 'spanish', 'Esta es mi oración de prueba de ejemplo que estoy poniendo en Google Translate para generar casos de prueba.'),
    ('fr', 'french', 'Ceci est mon exemple de phrase de test que je mets dans Google Translate pour générer des cas de test.'),
    ('it', 'italian', 'Questa è la mia frase di prova di esempio che sto inserendo in Google Translate per generare casi di test.'),
    ('ja', 'japanese', 'これは、テストケースを生成するためにGoogle翻訳に入力する私のテスト文の例です。'),
    ('ko', 'korean', '이것은 테스트 케이스를 생성하기 위해 Google Translate에 넣은 예제 테스트 문장입니다.'),
    ('lt', 'lithuanian', 'Tai yra mano bandomo sakinio pavyzdys, kurį dedu į „Google“ vertėją norėdamas sugeneruoti bandomuosius atvejus.'),
    ('nb', 'norwegian bokmal', 'Dette er mitt eksempel test setning som jeg legger i Google Translate for å generere testsaker.'),
    ('nl', 'dutch', 'Dit is mijn voorbeeldtestzin die ik in Google Translate zet om testcases te genereren.'),
    ('pl', 'polish', 'To jest moje przykładowe zdanie testowe, które umieszczam w Tłumaczu Google, aby wygenerować przypadki testowe.'),
    ('pt', 'portuguese', 'Esta é a minha frase de teste de exemplo que estou colocando no Google Translate para gerar casos de teste.'),
    ('ro', 'romanian', 'Acesta este exemplul meu de propoziție pe care îl introduc în Google Translate pentru a genera cazuri de testare.'),
    ('ru', 'russian', 'Это мое примерное тестовое предложение, которое я помещаю в Google Translate для создания тестовых случаев.'),
    ('uk', 'ukranian', 'Це мій приклад тестового речення, яке я вкладаю в Google Translate для створення тестових випадків.'),
    ('zh', 'chinese', '这是我输入Google Translate生成测试用例的示例测试语句。'),
    ('zh', 'chinese', '這是我輸入Google Translate生成測試用例的示例測試語句。'),
    ('af', 'afrikaans', 'Dit is my voorbeeldse toetssin wat ek in Google Translate plaas om toetsgevalle te genereer.'),
    ('sq', 'albanian', 'Kjo është fjalia ime e provës që po e vë në Google Translate për të gjeneruar raste testimi.'),
    ('hy', 'armenian', 'Սա իմ օրինակելի թեստային նախադասությունն է, որը ես դնում եմ Google Translate- ում ՝ թեստային դեպքեր առաջացնելու համար:'),
    ('eu', 'basque', 'Hau da Google Translate bertsioan jartzen ari naizen testeko esaldia. Test kasuak sortzeko.'),
    ('bn', 'bengali', 'এটি আমার উদাহরণ পরীক্ষার বাক্য যা পরীক্ষার কেসগুলি উত্পন্ন করার জন্য আমি গুগল অনুবাদে রাখছি।'),
    ('bg', 'bulgarian', 'Това е моето примерно изпитателно изречение, което вкарвам в Google Translate, за да генерирам тестови случаи.'),
    ('ca', 'catalan', 'Aquest és el meu exemple de frase de prova que vaig publicant a Google Translate per generar casos de prova.'),
    ('hr', 'croatian', 'Ovo je moja testna rečenica koju stavljam u Google Translate za generiranje testnih slučajeva.'),
    ('cs', 'czech', 'Toto je můj příklad zkušební věty, kterou vkládám do Překladače Google, abych generoval testovací případy.'),
    ('et', 'estonian', 'See on minu näidislause, mille panen testversioonide genereerimiseks Google''i tõlki.'),
    ('fi', 'finnish', 'Tämä on esimerkki testilauseestani, jonka laitan Google Translate -sovellukseen testitapausten luomiseksi.'),
    ('gu', 'gujarati', 'આ મારું ઉદાહરણ પરીક્ષણ વાક્ય છે કે જે હું પરીક્ષણનાં કેસો પેદા કરવા માટે Google અનુવાદમાં મૂકી રહ્યો છું.'),
    ('he', 'hebrew', 'זהו משפט המבחן הדוגמא שלי שאני מכניס ל- Google Translate כדי ליצור מקרי מבחן.'),
    ('hi', 'hindi', 'यह मेरा उदाहरण परीक्षण वाक्य है जो मैं परीक्षण मामलों को उत्पन्न करने के लिए Google अनुवाद में डाल रहा हूं।'),
    ('hu', 'hungarian', 'Ez a példakénti tesztmondat, amelyet a Google Fordítóba teszteket hozok létre.'),
    ('is', 'icelandic', 'Þetta er dæmi setningarpróf sem ég set í Google Translate til að búa til prófatilvik.'),
    ('id', 'indonesian', 'Ini adalah contoh kalimat pengujian yang saya masukkan ke Google Terjemahan untuk menghasilkan kasus uji.'),
    ('ga', 'irish', 'Is í seo mo phianbhreith tástála samplach atá á cur agam ar Google Translate chun cásanna tástála a ghiniúint.'),
    ('kn', 'kannada', 'ಪರೀಕ್ಷಾ ಪ್ರಕರಣಗಳನ್ನು ರಚಿಸಲು ನಾನು Google ಅನುವಾದಕ್ಕೆ ಹಾಕುತ್ತಿರುವ ನನ್ನ ಉದಾಹರಣೆ ಪರೀಕ್ಷಾ ವಾಕ್ಯ ಇದು.'),
    ('lv', 'latvian', 'Šis ir mans testa teikuma piemērs, kuru es ievietoju Google Translate, lai ģenerētu testa gadījumus.'),
    ('lb', 'luxembourgish', 'Dëst ass mäi Beispill Testsaz deen ech a Google Translate setzen fir Testfäll ze generéieren.'),
    ('ml', 'malayalam', 'ടെസ്റ്റ് കേസുകൾ സൃഷ്ടിക്കുന്നതിനായി ഞാൻ Google വിവർത്തനത്തിലേക്ക് ഇടുന്ന എന്റെ ഉദാഹരണ പരീക്ഷണ വാക്യമാണിത്.'),
    ('mr', 'marathi', 'हे माझे उदाहरण चाचणी वाक्य आहे जे मी चाचणी प्रकरणे व्युत्पन्न करण्यासाठी Google भाषांतर मध्ये टाकत आहे.'),
    ('fa', 'farsi', 'این جمله آزمایشی نمونه ای است که من برای تولید موارد آزمایشی در Google Translate قرار می دهم.'),
    ('sr', 'sanskrit', 'Ово је мој пример тестне реченице коју стављам у Гоогле Транслате да бих генерисао тест случајеве.'),
    ('si', 'sinhala', 'පරීක්ෂණ අවස්ථා උත්පාදනය කිරීම සඳහා මම ගූගල් පරිවර්තනයට ඇතුළත් කරන මගේ උදාහරණ පරීක්ෂණ වාක්‍යය මෙයයි.'),
    ('sk', 'slovak', 'Toto je môj príklad testovacej vety, ktorú vkladám do služby Prekladač Google, aby som vygeneroval testovacie prípady.'),
    ('sl', 'slovenian', 'To je moj primer testnega stavka, ki ga vstavljam v Google Translate za ustvarjanje preskusnih primerov.'),
    ('sv', 'swedish', 'Detta är mitt exempel på testmeningen som jag lägger in i Google Translate för att generera testfall.'),
    ('tl', 'tagalog', 'Ito ang aking halimbawang pangungusap na pagsubok na inilalagay ko sa Google Translate upang makabuo ng mga kaso ng pagsubok.'),
    ('ta', 'tamil', 'சோதனை நிகழ்வுகளை உருவாக்க நான் Google மொழிபெயர்ப்பில் இடும் எனது எடுத்துக்காட்டு சோதனை வாக்கியம் இது.'),
    ('tt', 'tatar', 'Бу минем сынау үрнәкләрен ясау өчен Google Translate''ка куйган сынау җөмләсе.'),
    ('te', 'telugu', 'పరీక్ష కేసులను రూపొందించడానికి నేను గూగుల్ ట్రాన్స్‌లేట్‌లో పెడుతున్న నా ఉదాహరణ పరీక్ష వాక్యం ఇది.'),
    ('th', 'thai', 'นี่คือประโยคทดสอบตัวอย่างของฉันที่ฉันใส่ลงใน Google Translate เพื่อสร้างกรณีทดสอบ'),
    ('tr', 'turkish', 'Bu, test senaryoları oluşturmak için Google Çeviri''ye koyduğum örnek test cümledim.'),
    ('ur', 'urdu', 'یہ میرا مثال آزمائشی جملہ ہے جو میں گوگل کے ترجمے میں ٹیسٹ کے معاملات پیدا کرنے کے لئے ڈال رہا ہوں۔'),
    ('vi', 'vietnamese', 'Đây là câu kiểm tra mẫu của tôi mà tôi đang đưa vào Google Dịch để tạo các trường hợp kiểm tra.'),
    ('yo', 'yoruba', 'Eyi ni idajọ idanwo mi ti Mo n fi sinu Tumọ-ọrọ Google lati ṣe agbekalẹ awọn ọran idanwo.')
    ;

SELECT lang_iso, lang_name, chajda_tsvector(lang_iso,doc) from example;
