CREATE EXTENSION IF NOT EXISTS pspacy;
SELECT spacy_lemmatize('zh',' "这是我输入Google Translate生成测试用例的示例测试语句。"' , lower_case=>True , remove_special_chars=>True , remove_stop_words=>True , add_positions=>True);
SELECT spacy_lemmatize('zh',' "这是我输入Google Translate生成测试用例的示例测试语句。"' , lower_case=>True , remove_special_chars=>True , remove_stop_words=>True , add_positions=>False);
SELECT spacy_lemmatize('zh',' "这是我输入Google Translate生成测试用例的示例测试语句。"' , lower_case=>True , remove_special_chars=>True , remove_stop_words=>False , add_positions=>True);
SELECT spacy_lemmatize('zh',' "这是我输入Google Translate生成测试用例的示例测试语句。"' , lower_case=>True , remove_special_chars=>True , remove_stop_words=>False , add_positions=>False);
SELECT spacy_lemmatize('zh',' "这是我输入Google Translate生成测试用例的示例测试语句。"' , lower_case=>True , remove_special_chars=>False , remove_stop_words=>True , add_positions=>True);
SELECT spacy_lemmatize('zh',' "这是我输入Google Translate生成测试用例的示例测试语句。"' , lower_case=>True , remove_special_chars=>False , remove_stop_words=>True , add_positions=>False);
SELECT spacy_lemmatize('zh',' "这是我输入Google Translate生成测试用例的示例测试语句。"' , lower_case=>True , remove_special_chars=>False , remove_stop_words=>False , add_positions=>True);
SELECT spacy_lemmatize('zh',' "这是我输入Google Translate生成测试用例的示例测试语句。"' , lower_case=>True , remove_special_chars=>False , remove_stop_words=>False , add_positions=>False);
SELECT spacy_lemmatize('zh',' "这是我输入Google Translate生成测试用例的示例测试语句。"' , lower_case=>False , remove_special_chars=>True , remove_stop_words=>True , add_positions=>True);
SELECT spacy_lemmatize('zh',' "这是我输入Google Translate生成测试用例的示例测试语句。"' , lower_case=>False , remove_special_chars=>True , remove_stop_words=>True , add_positions=>False);
SELECT spacy_lemmatize('zh',' "这是我输入Google Translate生成测试用例的示例测试语句。"' , lower_case=>False , remove_special_chars=>True , remove_stop_words=>False , add_positions=>True);
SELECT spacy_lemmatize('zh',' "这是我输入Google Translate生成测试用例的示例测试语句。"' , lower_case=>False , remove_special_chars=>True , remove_stop_words=>False , add_positions=>False);
SELECT spacy_lemmatize('zh',' "这是我输入Google Translate生成测试用例的示例测试语句。"' , lower_case=>False , remove_special_chars=>False , remove_stop_words=>True , add_positions=>True);
SELECT spacy_lemmatize('zh',' "这是我输入Google Translate生成测试用例的示例测试语句。"' , lower_case=>False , remove_special_chars=>False , remove_stop_words=>True , add_positions=>False);
SELECT spacy_lemmatize('zh',' "这是我输入Google Translate生成测试用例的示例测试语句。"' , lower_case=>False , remove_special_chars=>False , remove_stop_words=>False , add_positions=>True);
SELECT spacy_lemmatize('zh',' "这是我输入Google Translate生成测试用例的示例测试语句。"' , lower_case=>False , remove_special_chars=>False , remove_stop_words=>False , add_positions=>False);
SELECT spacy_lemmatize('zh',' "這是我輸入Google Translate生成測試用例的示例測試語句。"' , lower_case=>True , remove_special_chars=>True , remove_stop_words=>True , add_positions=>True);
SELECT spacy_lemmatize('zh',' "這是我輸入Google Translate生成測試用例的示例測試語句。"' , lower_case=>True , remove_special_chars=>True , remove_stop_words=>True , add_positions=>False);
SELECT spacy_lemmatize('zh',' "這是我輸入Google Translate生成測試用例的示例測試語句。"' , lower_case=>True , remove_special_chars=>True , remove_stop_words=>False , add_positions=>True);
SELECT spacy_lemmatize('zh',' "這是我輸入Google Translate生成測試用例的示例測試語句。"' , lower_case=>True , remove_special_chars=>True , remove_stop_words=>False , add_positions=>False);
SELECT spacy_lemmatize('zh',' "這是我輸入Google Translate生成測試用例的示例測試語句。"' , lower_case=>True , remove_special_chars=>False , remove_stop_words=>True , add_positions=>True);
SELECT spacy_lemmatize('zh',' "這是我輸入Google Translate生成測試用例的示例測試語句。"' , lower_case=>True , remove_special_chars=>False , remove_stop_words=>True , add_positions=>False);
SELECT spacy_lemmatize('zh',' "這是我輸入Google Translate生成測試用例的示例測試語句。"' , lower_case=>True , remove_special_chars=>False , remove_stop_words=>False , add_positions=>True);
SELECT spacy_lemmatize('zh',' "這是我輸入Google Translate生成測試用例的示例測試語句。"' , lower_case=>True , remove_special_chars=>False , remove_stop_words=>False , add_positions=>False);
SELECT spacy_lemmatize('zh',' "這是我輸入Google Translate生成測試用例的示例測試語句。"' , lower_case=>False , remove_special_chars=>True , remove_stop_words=>True , add_positions=>True);
SELECT spacy_lemmatize('zh',' "這是我輸入Google Translate生成測試用例的示例測試語句。"' , lower_case=>False , remove_special_chars=>True , remove_stop_words=>True , add_positions=>False);
SELECT spacy_lemmatize('zh',' "這是我輸入Google Translate生成測試用例的示例測試語句。"' , lower_case=>False , remove_special_chars=>True , remove_stop_words=>False , add_positions=>True);
SELECT spacy_lemmatize('zh',' "這是我輸入Google Translate生成測試用例的示例測試語句。"' , lower_case=>False , remove_special_chars=>True , remove_stop_words=>False , add_positions=>False);
SELECT spacy_lemmatize('zh',' "這是我輸入Google Translate生成測試用例的示例測試語句。"' , lower_case=>False , remove_special_chars=>False , remove_stop_words=>True , add_positions=>True);
SELECT spacy_lemmatize('zh',' "這是我輸入Google Translate生成測試用例的示例測試語句。"' , lower_case=>False , remove_special_chars=>False , remove_stop_words=>True , add_positions=>False);
SELECT spacy_lemmatize('zh',' "這是我輸入Google Translate生成測試用例的示例測試語句。"' , lower_case=>False , remove_special_chars=>False , remove_stop_words=>False , add_positions=>True);
SELECT spacy_lemmatize('zh',' "這是我輸入Google Translate生成測試用例的示例測試語句。"' , lower_case=>False , remove_special_chars=>False , remove_stop_words=>False , add_positions=>False);
SELECT spacy_tsvector('zh',' "這是我輸入Google Translate生成測試用例的示例測試語句。"');
SELECT spacy_tsvector('zh',' "這是我輸入Google Translate生成測試用例的示例測試語句。"');
