name: tests

on: [ push ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        sh install_dependencies.sh
        pip install flake8 pytest
        #- name: Lint with flake8
        #run: |
        #flake8 --ignore=E501,E123,E402 .
    - name: Test with pytest
      run: |
        export test_level=2
        export nval_lang=github
        pytest tests/test_augments.py
        pytest tests/test_bench.py
        pytest tests/test_golden.py
        pytest chajda --doctest-modules

  docker:
    strategy:
      matrix:
        POSTGRES_VERSION: [12, 13]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker
      run: |
        docker-compose build --build-arg BASE_IMAGE_VERSION=${{matrix.POSTGRES_VERSION}}
        docker-compose up -d --build
        sleep 20
        docker-compose exec -T db make installcheck
        docker-compose down
